# vim: shiftwidth=2
config:
  backup: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: link
actions:
  vim-plug: nvim --noplugin --headless +PlugClean +PlugInstall +qall
  fisher: ~/.config/fish/fisher_bootstrap
  fish_dotdrop: echo 'alias -s dotdrop $PWD/dotdrop.sh' | fish
dotfiles:
  nvim:
    dst: ~/.config/nvim
    src: config/nvim
    actions:
      - vim-plug
  bat:
    dst: ~/.config/bat
    src: config/bat
  fish:
    dst: ~/.config/fish
    src: config/fish
    actions:
      - fisher
      - fish_dotdrop
  htop:
    dst: ~/.config/htop
    src: config/htop
  bspwm:
    dst: ~/.config/bspwm
    src: config/bspwm
  lf:
    dst: ~/.config/lf
    src: config/lf
  yabai:
    dst: ~/.config/yabai
    src: config/yabai
  zathura:
    dst: ~/.config/zathura
    src: config/zathura
  skhd:
    dst: ~/.config/skhd
    src: config/skhd
  sxhkd:
    dst: ~/.config/sxhkd
    src: config/sxhkd
  karabiner:
    dst: ~/.config/karabiner
    src: config/karabiner
  neofetch:
    dst: ~/.config/neofetch
    src: config/neofetch
  kitty:
    dst: ~/.config/kitty
    src: config/kitty
  ripgrep:
    dst: ~/.config/ripgrep
    src: config/ripgrep
  rofi:
    dst: ~/.config/rofi
    src: config/rofi
  git:
    dst: ~/.gitconfig
    src: gitconfig
  gitignore:
    dst: ~/.gitignore_global
    src: gitignore_global
profiles:
  Cheshire-Cat.local:
    dotfiles:
      - fish
      - nvim
      - kitty
      - bat
      - htop
      - ripgrep
      - neofetch
      - lf
      - karabiner
      - skhd
      - yabai
      - git
      - gitignore
  juche:
    dotfiles:
      - fish
      - nvim
      - kitty
      - bat
      - htop
      - ripgrep
      - neofetch
      - lf
      - rofi
      - bspwm
      - sxhkd
      - zathura
      - git
      - gitignore
